### ISSUE TITLE
Die Option: „Zurück zur letzten Version“ + Widerrufen / Wiederholen aus iVocabulary 2 fehlt weiterhin in iVocabulary 3

### ISSUE THREAD

**Issue by 47ZTuewFC2m938A2VF9ziMr74** [chbeer/iVocabulary-Support#252]
Wenn in einem Vokabelheft seine Vokabeln einträgt und fälschlicherweise auf einmal alle Vokabeln löscht oder so, dann sind sie verschwunden, und man kann sie nicht zurückholen, und aus diesem Grund wäre es ganz gut, wenn man den Löschvorgang widerrufen kann oder zur letzten Version zurückkehren könnte. 

Oder ein Gast / ein Freund lernt gerade mit meinem Vokabelheft und nach seinem Training sollen die Ergebnisse wieder gelöscht werden bzw. zur ursprünglichen Version zurückkehren, ohne das meine Ergebnisse verloren gehen.

**Comment by chbeer** [comment]
Dies ist nicht möglich, da iVocabulary 3 nicht mit Dokumenten/Dateien arbeitet, sondern mit einer internen Datenbank. Diese Umstellung war der Umsetzung der Synchronisation geschuldet, bei der iVocabulary auf alle "Hefte" zugreifen können muss.

iVocabulary 3 bietet allerdings Undo/Redo-Support, womit das Löschen wiederhergestellt werden kann.

Für iVocabulary 4 ist geplant wieder Dokumente zu nutzen, womit dann auch Time Machine und "Zurück zur letzten Version" wieder funktionieren soll.
